### ISSUE TITLE
Custom Component: Bootstrap Radio buttons with Angular 9 and latest formio

### ISSUE THREAD

**Issue by dmenne** [formio/angular#494]
I had nasty versioning and infinite-loop problems with custom components when I started from the @merobal rating sample. So I started from scratch and created Really Large Bootstrap Buttons mainly for use on tablets.

https://github.com/dmenne/custom-radio

Feel free to try and test it.

**Comment by dmenne** [comment]
Issue in above custom component: 

- ngOnit is called 6 times when I open the editor

Well, that's progress, it was called infinitely often in earlier version (Reported by @merobal)

**Comment by travist** [comment]
This is great!  We should include this repository as an example in the Wiki so that people have a working example they can work off of.  As for the "infinite" issue... we will have a developer on our side investigate this problem.

**Comment by dmenne** [comment]
As I noted, the app called ngOnit 6 times, but then worked ok when the editor was opened. Today, I did a version update to 9.0.7, and after install of all node_modules, I ran into the infinite loop. 

However, after totally removing node_modules and reinstall, business was as usual again. Maybe this can give you a hint tracing down the problem.

**Comment by ullas1989** [comment]
I did angular version update to 9.0.7 today and infinite loop is not going away even after clearing node modules. I am thinking of going back to 9.0.6 now.

**Comment by dmenne** [comment]
Strange. Everything is ok for me with 9.0.7, but I definitively saw the infinite loop this morning. Keep me updated. Just a wild guest: 9.0.6 will also go into nirwana? Have you tested it?

**Comment by ullas1989** [comment]
I rollback my changes to last working version and tried updating angular cli.
@angular/cli                       9.0.6 -> 9.0.7           ng update @angular/cli

It worked fine on local but as soon as I deployed it a server, it started throwing infinite loop. I can probably check the build configuration or my package-lock.json to find out more about it.

So I am back to last stable version which is:
@angular/cdk                       9.1.1
@angular/cli                       9.0.6
@angular/core                      9.0.6
@ngrx/store                        8.6.0

Now I am getting infinite loop only when validations kick in and a grid component is present on the form. I think this was always happening with older version as well.

https://github.com/formio/angular-formio/issues/465

**Comment by dmenne** [comment]
I have updated my example for a [radio-button custom component](https://github.com/dmenne/custom-radio), with an additional chapter how to create custom component editors by modifiying  the JSON output of exisiting editors. 

A custom select box to switch between bootstrap button color styles is created.

**Comment by travist** [comment]
@dmenne we did resolve some infinite loops in our core renderer with the latest builds. Please try the latest versions and see if the problem persists. If so, then we will get it resolved quickly.

**Comment by dmenne** [comment]
I no have tried angular-formio 4.6.16, I had not seen the infinite recursion for 3 days. However, one thing I noted: Whenever I openend an custom editor, ngOnit was called 6 times before. Now, it is 7 times. Is that the "expected behavior"? Further than that, output looks ok at first glance.

**Comment by ullas1989** [comment]
@travist Still seeing infinite loop with angular-formio 4.6.17.

Issue comes up when there is a grid on the page and validations kick in. I will provide a sample app somewhere to show that.

**Comment by dmenne** [comment]
Interesting... that's why I now rarely see infinite loops, because I removed all validations - among other decorative stuff.

**Comment by merobal** [comment]
@travist the issue described in https://github.com/formio/angular-formio/issues/465 is still present with the latest version (angular-formio 4.6.17).

**Comment by jbarrus** [comment]
Not sure if this is related, but I'm seeing a problem with the data value field on select boxes. When I type something in it gets deleted and the console reports and infinite loop.

**Comment by travist** [comment]
Not sure it is related, but we did fix an issue with infinite loops last night with our latest builds. I am curious if the latest version resolves this issue.

**Comment by dmenne** [comment]
Browser is empty with error with these changes.

See https://github.com/dmenne/custom-radio/tree/issue494

```
Formio.js:1795 Uncaught ReferenceError: global is not defined
    at Object../node_modules/formiojs/Formio.js (Formio.js:1795)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/formiojs/components/address/Address.js (Address.js:58)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/formiojs/components/index.js (index.js:8)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/formiojs/formio.form.js (formio.form.js:75)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/formiojs/index.js (index.js:61)
    at __webpack_require__ (bootstrap:79)
client:52 [WDS] Live Reloading enabled.
```

**Comment by travist** [comment]
Yeah, we just heard from one of our developers about this.  We just submitted this pull request which we hope resolves the issue.  https://github.com/formio/formio.js/pull/2631

Is it possible for you to open up the ```node_modules/formiojs/Formio.js``` on your end and add those conditional statements and see if it resolves the issue for you.

Just some context on these changes.... we are working making our core renderer work in both ```import``` scenarios but also in using ```<script>``` tags and allow extension modules work with both. This has caused us to make some changes to support this which we are finding does not comply with all different ways of compiling the applications. Sorry for the churn, but it will reach stability very soon.

**Comment by travist** [comment]
I have an app that reproduces this now... I can verify on my end this solves the problem.  New build coming very soon.

**Comment by travist** [comment]
The error ^ was fixed with the latest Angular build. Sorry for the glitch.

**Comment by dmenne** [comment]
Fixed (at least the glitch).
Note that I have not seen the infinite loop for some time already, but still on every key press in one of the editors ngOnit is call 6 time (exactly, no variation). As I only made a copy of your editor, I assume that this occurs in your code too.

**Comment by travist** [comment]
I think the ngOnInit issue will need to be resolved separately. My response earlier was to other reports from other people about an infinite loop. I believe this thread was hijacked with that point which I hope is now resolved. The original issue you brought up with the ngOnInit is not fixed apparently and will still need investigation.

**Comment by merobal** [comment]
`ngOnInit` is called each time the form builder re-renders the layout. We experience the same, as long as the user types something in the edit form, the preview is being re-rendered. _(If you hit the API at `ngOnInit` I suggest doing caching at service layers.)_

**Comment by dmenne** [comment]
I had seen your suggestion to cache the service layer, that cures the symptoms as long there is no vaccine available. Calling the full constructor API 6 times at each keyboard press is not what Angular apps are supposed to do; calling a subservice e.g. for typeahead would be ok.

So please to fix this. It is also in the interest of form.io to encourage a cottage industry that creates use components.

**Comment by travist** [comment]
I agree we should not be doing this... I would need to dig in to investigate, but am currently tied up with other items. If someone from the community could investigate we would be very grateful. Otherwise, it will just need to wait until it makes it to the top of someones list here at Form.io.

**Comment by merobal** [comment]
So technically this issue is narrowed down to "ngOnInit is called 6-8 times" (similar to #507) and this is probably due formio refreshes the layout and re-renders itself more than once per update. It's not a big deal to native html components (almost unnoticed) but since Angular components may contain logic inside itself it's a noticeable issue.

Do you have any update on this?

**Comment by dmenne** [comment]
"ngOnInit is called 6-8 times" __on every key press__. This is not how Angular is supposed to work.

**Comment by merobal** [comment]
Yes, that is the issue, and I wanted to ping @travist to check this.
(Probably Formio updates the layout on every keypress and refreshes it 6-8 times per update. It's not a big deal for native html tags but a noticeable issue for Angular)

**Comment by travist** [comment]
@dmenne we all agree that this needs to be resolved. We are actually making significant improvements to our Angular libraries so it is possible this may be resolved. @Alena-Levina is leading up this effort so maybe she has an idea if this issue will be resolved or if she has noticed it.

**Comment by dmenne** [comment]
Welcome in our gang,   @Alena-Levina!

**Comment by Alena-Levina** [comment]
Hi @dmenne ! Sorry for the delayed response.

I've been reading this thread several times and still am a bit confused about how I should reproduce this issue.

I tried using our Form Builder from [angular-demo](https://github.com/formio/angular-demo) repo and was not able to notice any calls of Form Builder's `ngOnInit` during editing a Custom Component, please see the recording: https://monosnap.com/file/bdmOUmcvBhvEmWdf2s2QcNk4dLq4AX

Could you please provide me detailed steps which I need to take to be able to reproduce your issue?

Regards,
Alena

**Comment by dmenne** [comment]
Dear Alena,

maybe you could try

https://github.com/dmenne/custom-radio.

I think there is a logging output in it. Called 3 times on keypress, 3 times on release when any editor is open.

If you cannot reproduce with the current version, I will check again. Sorry, I have not looked into this for 6 weeks, so it may be ok with the current version.

Dieter

**Comment by dmenne** [comment]
https://github.com/formio/angular-formio/issues/507#issuecomment-627208014

Nothing improved.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
